### ISSUE TITLE
Alfred workflow can't find my meetings

### ISSUE THREAD

**Issue by kinglycodes** [caleb531/open-conference-url#1]
Hey Caleb,
the alfred workflow seems not working properly on my mac.
It doesn't find any meetings in my calendar.

Could you please help me?

thanks
Stefan

**Comment by nonameolsson** [comment]
I have this problem also. It only shows default search options. 
![image](https://user-images.githubusercontent.com/1493018/102878546-b8946880-4448-11eb-998e-5f33f4f92f04.png)

**Comment by tiems90** [comment]
Same issue here; with the exact same screens as @nonameolsson has above.

**Comment by tiems90** [comment]
@nonameolsson I noticed a fix here:
https://www.alfredforum.com/topic/16215-open-conference-url-launch-the-zoommeet-call-for-your-next-calendar-event/?do=findComment&comment=82854

It requires a modification to line 77 of `cache.py`

At least the cache is updated now, but I'm not sure I can link it to my meetings yet.

**Comment by tiems90** [comment]
Actually, I resolved the issue by just downloading the latest version from the github. 
It looks like the version I had downloaded was out of date.

**Comment by caleb531** [comment]
@tiems90 Thanks for the feedback. This should be fixed in the latest version, as you found. As such, I am closing this ticket.

Please open a new ticket if you encounter any additional issues.
