### ISSUE TITLE
Error message due to untrusted developer for `icalBuddy`

### ISSUE THREAD

**Issue by birnstiel** [caleb531/open-conference-url#11]
The workflow doesn't run out-of-the-box since `icalBuddy` is not from a trusted developer. A possible workaround is to

- open the workflow in the finder (right-click on it in the list -> Open in Finder)
- go into `ocu/`, right-click `icalBuddy` and select "Open"
 
This allows running the executable despite this security warning.

A possible alternative would be: first try to use a homebred-installed version and if that's not available fall back to the included version second (and perhaps issue a one-time warning).

**Comment by caleb531** [comment]
@birnstiel The reason I currently package `icalBuddy` with the workflow is so that users won't be required to install Homebrew to get it. But this isn't a bad idea, provided that it perhaps only benefits users who already have Homebrew installed. What do you think?

**Comment by birnstiel** [comment]
Yes I get that and it makes sense. But I think currently everyone will get this issue with the developer credentials. If you check for a home-brew version first, this would avoid the issue for people that have `icalBuddy` installed via homebrew, also after future updates of your workflow. Those that don't have it still have to fix it either as I explained above, or by installing `icalBuddy` with homebrew.

**Comment by caleb531** [comment]
@birnstiel I just released v4.0.0-beta.1 with the new logic to prefer Homebrew icalBuddy. Can you please test it out and let me know if you still receive an Untrusted Developer error?

https://github.com/caleb531/open-conference-url/releases/tag/v4.0.0-beta.1

Thanks so much,
Caleb

**Comment by birnstiel** [comment]
If I just install it, I get the warning again (as expected), but once I install icalBuddy with `brew install ical-buddy`, it works without issues.

**Comment by caleb531** [comment]
@birnstiel Got it, thanks so much! I am currently experimenting with replacing icalBuddy with a pure-AppleScript solution. We'll see how it goes!

**Comment by caleb531** [comment]
@birnstiel Okay, I just completed a major refactor of the codebase, with two substantial changes:

1. icalBuddy has now been replaced by an AppleScript which uses the `Foundation` and `EventKit` libraries (`ocu/get-calendar-events.applescript`, if you're curious)
2. The caching mechanism has been completely removed, so you no longer see stale results when running `conf`

Both of these are pretty sizable changes, so I was wondering if you'd be so kind to try beta 2 of the workflow and let me know how it works for you:
https://github.com/caleb531/open-conference-url/releases/tag/v4.0.0-beta.2

Thanks again,
Caleb

**Comment by caleb531** [comment]
@birnstiel Also, I just recently released v4.0.0-beta.3 with a fix for how the Zoom URLs are built. Again, any testing you could do on the latest beta would be greatly appreciated. I would love to have a second tester (besides myself) before releasing v4 stable.

**Comment by caleb531** [comment]
@birnstiel Okay, so I decided to release v4.0.0 stable because I felt it was actually pretty ready, having used and tested the betas myself over the past few weeks. 😅

Since v4 completely replaces icalBuddy, I am closing this issue, but please don't hesitate to [create a new issue](https://github.com/caleb531/open-conference-url/issues/new) if you run into any trouble on v4 stable.

https://github.com/caleb531/open-conference-url/releases/tag/v4.0.0

**Comment by birnstiel** [comment]
tried it briefly and it works! thanks for implementing it! 👍
