### ISSUE TITLE
Time Threshold does not have any effect

### ISSUE THREAD

**Issue by Acidham** [caleb531/open-conference-url#18]
When I am setting Time Threshold to 20 minutes, the workflow shows all events in a day and not as expected within the next 20 minutes. 

My time format is set to: HH:MM:SS (24hrs)

**Comment by Acidham** [comment]
I did not change the default value. 

<img width="577" alt="Screenshot 2022-10-18 at 21 21 16" src="https://user-images.githubusercontent.com/17712121/196524406-283d4761-cd6e-44ca-aa62-78fcc8a3e4f8.png">

**Comment by caleb531** [comment]
@Acidham Hm, that is strange. May I ask what timezone you are in? And also what is your system-set language/locale?

**Comment by Acidham** [comment]
> May I ask what timezone you are in? 
```
❯ python3 -c 'import time;print(time.tzname)'
('CET', 'CEST')
```
 And also what is your system-set language/locale?

```
❯ python3 -c 'import locale;print(locale.getdefaultlocale())'
('en_US', 'UTF-8')
```

**Comment by caleb531** [comment]
@Acidham Sorry for the delay in replying. I've been thinking about this ever since you sent your timezone/locale details above. 

I've reviewed the code that does the time computation, and I can't see how the minutes can be interpreted any other way than what is correct. So I suspect the discrepancy is stemming from the data in one of your calendar events (which should always be local time, based on how I'm retrieving them, but maybe not in your case). 🤷‍♂️😅

**Comment by Acidham** [comment]
I tried to debug your code on my side, but after upgrading to macOS 13.0 the Workflow stopped working. It seems osascript is stuck/running forever.

**Comment by caleb531** [comment]
@Acidham Oh, sorry to hear that. I have not yet upgraded to macOS Ventura, but I am planning to soon. I'll make a note to debug this workflow when I'm done upgrading (I use it myself, after all).

**Comment by caleb531** [comment]
@Acidham After further research, try running `xcode-select --install` in the Terminal to see if Apple's Command Line Tools need to be reinstalled:

```sh
xcode-select --install
```

Follow the prompts if it asks you to install the Apple Command Line Tools again. Once everything downloads and installs, that may resolve the post-upgrade issues.

**Comment by Acidham** [comment]
I already did that for my other workflows. But yours is not working and I am not sure if it is related to Ventura.

when I try to execute the apple script nothing happens and ScriptEditor need Force Quit to stop

**Comment by caleb531** [comment]
@Acidham Hmm, how many calendars do you have enabled? On average, how many calendar events do you have per day in the Calendar app

One other thing you can try is making sure that Alfred has the appropriate permissions to run the workflow. Not sure if "Terminal" will need the same permissions, but you can probably play around and see if anything works better. 😅

<img width="477" alt="Screenshot 2022-10-26 at 8 45 59 PM" src="https://user-images.githubusercontent.com/872474/198186810-53f22a39-31d0-4da4-8ac4-6d2513daa1b3.png">

**Comment by Acidham** [comment]
For sure, Privacy&Security is set up in the right way. 

What I found out after debugging your code (event.py, after 5 min wait time) is that all calendars will be loaded also the ones which are not set to active in calendar app (e.g. Family calendars). 

Is there must be a way to tell the AS which calendar to load?

**Comment by caleb531** [comment]
@Acidham That should be doable. Will take some work on my part, though. I'll create a separate issue for this, and tag you so you can follow the progress (as I will eventually want you to test the beta version).

**Comment by Acidham** [comment]
>  (as I will eventually want you to test the beta version)

coun't me in!

**Comment by caleb531** [comment]
Now that #19 is taken care of, please let me know if this time threshold quirk is still present for you.

**Comment by caleb531** [comment]
@Acidham Just want to follow up on this: are you still experiencing issues with the time threshold?

**Comment by Acidham** [comment]
Good that, you ask. The time threshold does not work. The workflow shows all event in the current day and not as expected in the configured time threshold.

**Comment by caleb531** [comment]
@Acidham Interesting. I still want to get to the root of this issue, and since I am unable to reproduce the issue myself, can you please [send me an email](https://calebevans.me/contact/) and perhaps we can schedule a Zoom call? I think some live-debugging of the workflow code on your end would really help to identity what is going on.

**Comment by Acidham** [comment]
It is a bit weir'ed .... Any number below 17 min is not working, everything above is working. You may change some numbers below 17 min to reproduce.

**Comment by caleb531** [comment]
@Acidham Hm, still can't reproduce on my end by changing Time Threshold to some number below 17. But of course, you'll get the "All Events" view if, say, you change the threshold to 1 minute, but the meeting is still 2 or more minutes away.

For the event you're testing with, I have three questions:

1. What does the result subtitle say is the start time of that event?
2. What does your system current time say at the moment you answer question (1) above?
3. What is your configured time threshold when testing all this?

The logic for the time range calculation isn't complicated, so I would expect the discrepancy would need to come from some mismatch between the system's current time and the start time of the event.

```python
# Return True if the given date/time object is within the acceptable tolerance
# range (e.g. within the next 15 minutes OR in the last 15 minutes); if not,
# return False
def is_time_within_range(event_datetime, event_time_threshold_mins):
    current_datetime = datetime.now()
    event_time_threshold = timedelta(minutes=event_time_threshold_mins)
    min_datetime = (event_datetime - event_time_threshold)
    max_datetime = (event_datetime + event_time_threshold)
    if min_datetime <= current_datetime <= max_datetime:
        return True
    else:
        return False
```

**Comment by Acidham** [comment]
I think I found the issue after debugging. Your logic line 104 is saying `elif all_events and not upcoming_events:` when upcomming_events (no events found in threshold) use all events. 

And shame on me, the workflow result is stating exactly this, "Showing all Calendar Events". But this "feature" was somehow not expected and therefore I was confused.

**Comment by caleb531** [comment]
@Acidham It's alright! I actually realized a few days ago that the wording isn't clear, and have pushed 0b6cb8a7923a7ddc5f9703a6e87866bee0d5c710 to improve the wording. I may still tweak this wording a bit more to make things even more clear.

All that to say, the language will be clearer in the next release of the workflow.

**Comment by Acidham** [comment]
did you receive my email re 24/12 hour clock switch?
