### ISSUE TITLE
Specify which calendars to read from

### ISSUE THREAD

**Issue by caleb531** [caleb531/open-conference-url#19]
From @Acidham via #18:

> What I found out after debugging your code (event.py, after 5 min wait time) is that all calendars will be loaded also the ones which are not set to active in calendar app (e.g. Family calendars).

> Is there to tell the AS which calendar to load?

I agree this would be a great feature. It should definitely be feasible, as the AppleScript I'm using originally had logic to filter by specific calendars. However, that logic was hardcoded into the AppleScript itself, so special code must be written to make this functionality user-configurable.

The scope of this enhancement is to add a new Configuration Field to allow the user to specify specific calendars for which to fetch events. If the field is blank, the workflow will fetch from all calendars.

The goal of this enhancement is to provide a means of improving performance for users with a particularly large number of calendar events across all their calendars.

**Comment by caleb531** [comment]
@Acidham So this ended up being a lot easier to implement than I thought. I've attached the beta below (enclosed inside a ZIP file).

I've added a new "Calendars" configuration field where you can specify a comma-separated list of the calendar names you want the workflow to pull from. If you leave the field blank, the workflow will search from all calendars in the Calendar app.

<img width="446" alt="Screenshot 2022-10-27 at 1 38 00 PM" src="https://user-images.githubusercontent.com/872474/198393029-f39c1278-43e9-4cc5-b12e-f6ef6efaf6a3.png">

Please try it and let me know how it works for you. I've tested it myself in the cases of one calendar, multiple calendars, and no calendars specified (i.e. implied all).

[Open Conference URL (Alfred 5).alfredworkflow.zip](https://github.com/caleb531/open-conference-url/files/9882970/Open.Conference.URL.Alfred.5.alfredworkflow.zip)

**Comment by Acidham** [comment]
Performance is back! The workflow is now showing up in milliseconds!

**Comment by caleb531** [comment]
@Acidham Great! I've just released v5.2.0 with this new configuration field (the code is identical to the beta, so only upgrade if you have OCD about it lol).

https://github.com/caleb531/open-conference-url/releases/tag/v5.2.0

**Comment by AlexanderWillner** [comment]
> I've added a new "Calendars" configuration field where you can specify a comma-separated list of the calendar names you want the workflow to pull from. If you leave the field blank, the workflow will search from all calendars in the Calendar app.

In version 4.0.0 I stopped the script after 10 Minutes and high CPU load. Is it possible to use the Calendar configuration in this version as well?

**Comment by AlexanderWillner** [comment]
Still using version 4. However, just wanted to know whether the configuration parameter is available with the old version as well. anyways, I will upgrade to version 5 eventually…

**Comment by caleb531** [comment]
@AlexanderWillner So the configuration system is [one of Alfred 5's new features](https://www.alfredapp.com/help/workflows/workflow-configuration/), and this workflow leverages that to make tweaking the workflow more streamlined and uniform. Under the hood though, the configuration values are exposed to the code as environment variables. 

So, if you are feeling adventurous, it should be possible to replace the contents of your Alfred 4 workflow (i.e. the `*.py` and `*.applescript` files, everything except the `*.plist`) files with the contents of the Alfred 5 workflow. If all goes well, everything should just work. If not, it may require some tweaks to the code. **But do remember to export / back up the workflow before you get started.** And keep in mind, I do not officially support modifications this way.

The environment variable for the new Calendar Names option is called `calendar_names`.
