### ISSUE TITLE
needs privacy permissions for both terminal and calendar

### ISSUE THREAD

**Issue by msdisme** [caleb531/open-conference-url#22]
Installed and saw a popup to grant privacy permissions - I must have hit enter and it went away very quickly so I missed the text so I only gave calendar access to Alfred 5.    It would be great if the readme github page mentioned both.  (If I my github is not too rusty I will do a PR against the readme.)

**Comment by caleb531** [comment]
@msdisme Oh, good catch! If you have a time, I would gladly accept a PR noting that in the README (however you see fit). 🙂
