### ISSUE TITLE
AppleScript error on macOS Ventura

### ISSUE THREAD

**Issue by xzha0006** [caleb531/open-conference-url#28]
The get-calendar-events.applescript under ocu/calendars directory can't be executed. It throws "subprocess.CalledProcessError: Command '['osascript', '/.../ocu/calendars/get-calendar-events.applescript']' returned non-zero exit status 1." 
Overwriting it with the get-calendar-events.applescript under /ocu directory fixed the issue.

**Comment by caleb531** [comment]
@xzha0006 What version of the workflow are you using? I'm pretty sure I already fixed this in v7.1.0, so please try downloading the latest version of the workflow (v7.1.2):

https://github.com/caleb531/open-conference-url/releases/tag/v7.1.2

**Comment by xzha0006** [comment]
Hi @caleb531 , I am using v7.1.2 for sure. Could you double-check that? Looks like there is a deprecated calendar API in the applescript sitting under /calendar.

**Comment by caleb531** [comment]
Hi @xzha0006,

Oh interesting. I will check tomorrow for sure!

Out of curiosity: are you running macOS Sonoma? Or an older version of macOS?

-Caleb

**Comment by xzha0006** [comment]
I am using Ventura. 
Btw, this workflow is a gem. Thanks for developing it!

**Comment by caleb531** [comment]
@xzha0006 So I think that explains the problem for me. I recently fixed #27 (inability to grant Alfred full calendar access) by replacing a deprecated AppleScript call to `requestAccessToEntityType` with `requestFullAccessToEventsWithCompletion`. However, I didn't realize that [per the docs](https://developer.apple.com/documentation/eventkit/ekeventstore/4162272-requestfullaccesstoeventswithcom), `requestFullAccessToEventsWithCompletion` only works on macOS Sonoma and newer.

I've pushed out v7.1.3-beta.1 with a fix for this. Basically, if I get an error calling `requestFullAccessToEventsWithCompletion`, I will fall back to `requestAccessToEntityType` that should work on macOS Ventura and earlier. Please try the workflow at the link below, and let me know how it works for you.

https://github.com/caleb531/open-conference-url/releases/tag/v7.1.3-beta.1

**Comment by xzha0006** [comment]
@caleb531 the beta version works fine. Thanks!

**Comment by caleb531** [comment]
@xzha0006 Excellent! I have just released the stable v7.1.3 release (no changes since the beta 1 version you tested). With that, I will be closing this issue now, but let me know if you run into any more issues!

https://github.com/caleb531/open-conference-url/releases/tag/v7.1.3
