### ISSUE TITLE
Add Slack to default conference domains

### ISSUE THREAD

**Issue by LinuxNtwrkng** [caleb531/open-conference-url#29]
Not an issue but as I can't seem to find where it's specified, could we add `app.slack.com` to the default "conference domains" list?

This would allow someone to just add the Slack huddle URL (obtained by clicking "copy huddle link" from any Slack channel) to a recurring calendar event for regularly scheduled Slack huddles without further modification.

**Comment by caleb531** [comment]
@LinuxNtwrkng That's a great idea! You are correct that it's not currently part of the default conference URLs, however you can easily add it for your installed workflow in Alfred's Workflow Configuration screen. To get there, visit:

_Alfred Preferences > Workflow > Open Conference URL > click the "Configure Workflow..." button_

<img width="306" alt="Screenshot 2023-10-27 at 1 51 40 PM" src="https://github.com/caleb531/open-conference-url/assets/872474/a55f92c5-8ae2-404b-97f0-1553dd43dc29">

<img width="1180" alt="Screenshot 2023-10-27 at 1 51 06 PM" src="https://github.com/caleb531/open-conference-url/assets/872474/3f22537f-5ee1-42ea-be97-ed89e6fd143b">

At any rate, yes, I will make a note to add `app.slack.com` to the default list. 🙂

**Comment by LinuxNtwrkng** [comment]
I did add it to my own workflow already but I thought it might be a nice enhancement for future users of this very useful workflow.  Thank you!

**Comment by caleb531** [comment]
@LinuxNtwrkng Okay, I've added support for Slack URLs in the latest v7.1.4-beta.1—can you please try it out? If it works well for you, I'll publish a stable release.

https://github.com/caleb531/open-conference-url/releases/tag/v7.1.4-beta.1

**Comment by LinuxNtwrkng** [comment]
@caleb531 Just tested and worked fine for me.  Thanks!

**Comment by caleb531** [comment]
@LinuxNtwrkng Fantastic, thank you for confirming! I have just released a stable v7.1.4 release with support for Slack conference URLs out of the box, now:
https://github.com/caleb531/open-conference-url/releases/tag/v7.1.4

Therefore, closing this thread as _Completed_. 🙂
