### ISSUE TITLE
Script running for too long

### ISSUE THREAD

**Issue by Avivbens** [caleb531/open-conference-url#32]
Hi 👋 

I've been using this amazing workflow for a while, but for the past week, I've been getting some odd delays from it. 
Seems like the workflow running for like a full minute until showing some results:

![CleanShot 2024-04-10 at 23 06 45@2x](https://github.com/caleb531/open-conference-url/assets/77183871/5094a4a9-5d4f-4bc0-8676-3d6629581972)

I'm on the latest version, currently `v7.1.4`
MacOS version: `14.4.1` Sonoma

**Comment by caleb531** [comment]
@Avivbens Interesting. Can you try enabling the workflow's [icalBuddy integration](https://github.com/caleb531/open-conference-url?tab=readme-ov-file#use-icalbuddy)? That tends to have much better performance than the default AppleScript-based mode.

**Comment by Avivbens** [comment]
Works PERFECT now 👍 

Thanks man, really appreciate 🙏 

### NOTE
BTW, [here is a nice one too](https://github.com/Avivbens/alfred-search-bookmark) you might find useful 😉
